# Access to host network is required to send WOL magic packets
controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: dispatcharr
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.18.1-20260206020542
          # use this when IPv6 is disabled in you setyup
          # see https://github.com/TimWolla/docker-adminer/issues/30
          # args:
          #   - php
          #   - -S
          #   - 0.0.0.0:8080
          #   - -t
          #   - /var/www/html
# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 9191

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
